# Generated by Django 4.1.5 on 2023-01-30 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['question__ordering'], 'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['ordering'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'verbose_name': 'опрос', 'verbose_name_plural': 'опросы'},
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Ответ пользователя', 'verbose_name_plural': 'Ответы пользователей'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='djf.question', verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='value',
            field=models.TextField(help_text='Значение ответа, данного пользователем', verbose_name='значение'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.TextField(blank=True, help_text='Если тип поля — радио, выбор или множественный выбор, заполните параметры, разделенные запятыми. Например: мужчина, женщина', null=True, verbose_name='choices'),
        ),
        migrations.AlterField(
            model_name='question',
            name='help_text',
            field=models.CharField(blank=True, help_text='Здесь вы можете добавить текст справки', max_length=200, null=True, verbose_name='help text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='key',
            field=models.CharField(blank=True, help_text='Уникальный ключ для этого вопроса. Заполните поле, если вы хотите использовать его для автоматической генерации', max_length=225, null=True, unique=True, verbose_name='key'),
        ),
        migrations.AlterField(
            model_name='question',
            name='label',
            field=models.CharField(help_text='Введите свой вопрос здесь', max_length=500, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='question',
            name='ordering',
            field=models.PositiveIntegerField(default=0, help_text='Определяет порядок вопросов в опросах', verbose_name='Выбор'),
        ),
        migrations.AlterField(
            model_name='question',
            name='required',
            field=models.BooleanField(default=True, help_text='Если True, пользователь должен дать ответ на этот вопрос', verbose_name='Обязательный'),
        ),
        migrations.AlterField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='djf.survey', verbose_name='Опрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type_field',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Text'), (1, 'Number'), (2, 'Radio'), (3, 'Select'), (4, 'Multi Select'), (5, 'Text Area'), (6, 'URL'), (7, 'Email'), (8, 'Date'), (9, 'Rating')], verbose_name='тип поля ввода'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='can_anonymous_user',
            field=models.BooleanField(default=False, help_text='Если True, пользователь без аутентификации может пройти опрос', verbose_name='Анонимный опрос'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='deletable',
            field=models.BooleanField(default=True, help_text='Если False, пользователь не может удалить запись', verbose_name='Удаляемый'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='duplicate_entry',
            field=models.BooleanField(default=False, help_text='Если True, пользователь может повторно отправить', verbose_name='Несколько представлений'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='editable',
            field=models.BooleanField(default=True, help_text='Если False, пользователь не может редактировать запись', verbose_name='Редактируемый'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='private_response',
            field=models.BooleanField(default=False, help_text='Если True, только администратор и владелец могут получить доступ', verbose_name='частный ответ'),
        ),
    ]
